[build]
  command = "pnpm build:frontend"
  publish = "apps/frontend/dist/client"
  ignore = "pnpm dlx turbo query affected --base=$CACHED_COMMIT_REF --packages @jeius-portfolio/frontend --exit-code"

[build.environment]
  NODE_VERSION = "24"

[functions]
  directory = "apps/frontend/.netlify/functions"

[images]
  remote_images = ["https://vpzsxbxfpmkzeefypjmw\\.supabase\\.co/storage/v1/object/public/.*"]